services:
  - type: web
    name: biscuitshop
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn biscuitshop.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: biscuitshop.settings
      - key: DEBUG
        value: "False"
      - key: ENV_MODE
        value: "production"

      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false 
      
      
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

      
      - key: SANDBOX_MVOLA_CLIENT_ID
        sync: false
      - key: SANDBOX_MVOLA_SECRET_KEY
        sync: false
      - key: SANDBOX_MVOLA_API_URL
        value: "https://api.sandbox.mvola.mg"
      - key: SANDBOX_MVOLA_ACCESS_TOKEN_ENDPOINT
        sync: false
      - key: SANDBOX_MVOLA_REVOKE_ENDPOINT
        sync: false
      - key: SANDBOX_MVOLA_PARTNER_MSISDN
        sync: false
      - key: MVOLA_PARTNER_NAME
        sync: false
      - key: MVOLA_API_SCOPE
        value: "EXT_INT_MVOLA_SCOPE"