name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Set up Python üêç
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests üß™
        env:
          DJANGO_SETTINGS_MODULE: biscuitshop.settings
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SANDBOX_MVOLA_CLIENT_ID: ${{ secrets.MVOLA_CLIENT_ID }}
          SANDBOX_MVOLA_CLIENT_SECRET: ${{ secrets.MVOLA_CLIENT_SECRET }}
          CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          DEBUG: ${{vars.DEBUG}}
          ALLOWED_HOSTS: ${{vars.ALLOWED_HOSTS}}
          ENV_MODE: ${{vars.ENV_MODE}}
          SANDBOX_MVOLA_API_URL: ${{vars.MVOLA_API_URL}}
          SANDBOX_MVOLA_ACCESS_TOKEN_ENDPOINT: ${{vars.MVOLA_ACCESS_TOKEN_ENDPOINT}}
          SANDBOX_MVOLA_REVOKE_ENDPOINT: ${{vars.MVOLA_REVOKE_ENDPOINT}}
          SANDBOX_MVOLA_PARTNER_MSISDN: ${{vars.MVOLA_PARTNER_MVOLA}}
          MVOLA_PARTNER_NAME: ${{vars.MVOLA_PARTNER_NAME}}
          MVOLA_API_SCOPE: ${{vars.MVOLA_API_SCOPE}}

        run: |
          python manage.py test